/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author H
 */
public class them_Thuoc_Tinh extends javax.swing.JFrame {

    /**
     * Creates new form them_Thuoc_Tinh
     */
    public them_Thuoc_Tinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente2 = new swing.PanelGradiente();
        panelBorder6 = new swing.PanelBorder();
        jLabel4 = new javax.swing.JLabel();
        panelBorder7 = new swing.PanelBorder();
        rdoThuonghieu1 = new javax.swing.JRadioButton();
        rdoChatlieu1 = new javax.swing.JRadioButton();
        rdoNSX1 = new javax.swing.JRadioButton();
        rdoMausac1 = new javax.swing.JRadioButton();
        rdoSize1 = new javax.swing.JRadioButton();
        rdodanhmuc1 = new javax.swing.JRadioButton();
        panelBorder8 = new swing.PanelBorder();
        jTextField2 = new javax.swing.JTextField();
        btn_them1 = new swing.MyButton();
        btn_xoa1 = new swing.MyButton();
        btn_LamMoi1 = new swing.MyButton();
        Btn_capNhat1 = new swing.MyButton();
        panelBorder9 = new swing.PanelBorder();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        panelBorder10 = new swing.PanelBorder();
        searchText2 = new swing.SearchText();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGradiente2.setColorPrimario(new java.awt.Color(204, 255, 255));

        panelBorder6.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText(" Nhập Tên");
        panelBorder6.add(jLabel4);
        jLabel4.setBounds(60, 60, 250, 30);

        panelBorder7.setBackground(new java.awt.Color(255, 255, 255));

        rdoThuonghieu1.setBackground(new java.awt.Color(255, 255, 255));
        rdoThuonghieu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoThuonghieu1.setText("Thương hiệu");
        rdoThuonghieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoThuonghieu1ActionPerformed(evt);
            }
        });
        panelBorder7.add(rdoThuonghieu1);
        rdoThuonghieu1.setBounds(270, 100, 110, 40);

        rdoChatlieu1.setBackground(new java.awt.Color(255, 255, 255));
        rdoChatlieu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoChatlieu1.setText("Chất liệu");
        rdoChatlieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoChatlieu1ActionPerformed(evt);
            }
        });
        panelBorder7.add(rdoChatlieu1);
        rdoChatlieu1.setBounds(30, 30, 110, 40);

        rdoNSX1.setBackground(new java.awt.Color(255, 255, 255));
        rdoNSX1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoNSX1.setText("Nhà sản xuất");
        rdoNSX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNSX1ActionPerformed(evt);
            }
        });
        panelBorder7.add(rdoNSX1);
        rdoNSX1.setBounds(150, 30, 110, 40);

        rdoMausac1.setBackground(new java.awt.Color(255, 255, 255));
        rdoMausac1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoMausac1.setText("Màu sắc");
        rdoMausac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMausac1ActionPerformed(evt);
            }
        });
        panelBorder7.add(rdoMausac1);
        rdoMausac1.setBounds(270, 30, 110, 40);

        rdoSize1.setBackground(new java.awt.Color(255, 255, 255));
        rdoSize1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoSize1.setText("Size");
        rdoSize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSize1ActionPerformed(evt);
            }
        });
        panelBorder7.add(rdoSize1);
        rdoSize1.setBounds(30, 100, 110, 40);

        rdodanhmuc1.setBackground(new java.awt.Color(255, 255, 255));
        rdodanhmuc1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdodanhmuc1.setText("Danh mục");
        rdodanhmuc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdodanhmuc1ActionPerformed(evt);
            }
        });
        panelBorder7.add(rdodanhmuc1);
        rdodanhmuc1.setBounds(150, 100, 110, 40);

        panelBorder6.add(panelBorder7);
        panelBorder7.setBounds(370, 20, 450, 170);

        panelBorder8.setBackground(new java.awt.Color(255, 255, 255));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setBorder(null);
        panelBorder8.add(jTextField2);
        jTextField2.setBounds(10, 0, 230, 50);

        panelBorder6.add(panelBorder8);
        panelBorder8.setBounds(60, 90, 250, 50);

        btn_them1.setBackground(new java.awt.Color(125, 224, 237));
        btn_them1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_them1.setText("Thêm");
        btn_them1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_them1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_them1ActionPerformed(evt);
            }
        });
        panelBorder6.add(btn_them1);
        btn_them1.setBounds(1010, 50, 120, 31);

        btn_xoa1.setBackground(new java.awt.Color(125, 224, 237));
        btn_xoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tay.png"))); // NOI18N
        btn_xoa1.setText("Xóa");
        btn_xoa1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_xoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoa1ActionPerformed(evt);
            }
        });
        panelBorder6.add(btn_xoa1);
        btn_xoa1.setBounds(1010, 130, 120, 31);

        btn_LamMoi1.setBackground(new java.awt.Color(125, 224, 237));
        btn_LamMoi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        btn_LamMoi1.setText("Làm Mới");
        btn_LamMoi1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_LamMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoi1ActionPerformed(evt);
            }
        });
        panelBorder6.add(btn_LamMoi1);
        btn_LamMoi1.setBounds(860, 50, 120, 31);

        Btn_capNhat1.setBackground(new java.awt.Color(125, 224, 237));
        Btn_capNhat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/floppy-disk.png"))); // NOI18N
        Btn_capNhat1.setText("Cập nhật");
        Btn_capNhat1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_capNhat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_capNhat1ActionPerformed(evt);
            }
        });
        panelBorder6.add(Btn_capNhat1);
        Btn_capNhat1.setBounds(860, 130, 120, 31);

        panelGradiente2.add(panelBorder6);
        panelBorder6.setBounds(10, 50, 1160, 230);

        panelBorder9.setBackground(new java.awt.Color(204, 204, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(204, 204, 255));
        jTable2.setRowHeight(25);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        panelBorder9.add(jScrollPane2);
        jScrollPane2.setBounds(0, 70, 1160, 250);

        panelBorder10.setBackground(new java.awt.Color(255, 255, 255));

        searchText2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelBorder10.add(searchText2);
        searchText2.setBounds(10, 0, 240, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_24px.png"))); // NOI18N
        panelBorder10.add(jLabel5);
        jLabel5.setBounds(264, 0, 40, 50);

        panelBorder9.add(panelBorder10);
        panelBorder10.setBounds(790, 10, 300, 50);

        panelGradiente2.add(panelBorder9);
        panelBorder9.setBounds(10, 300, 1160, 320);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panelGradiente2.add(jPanel2);
        jPanel2.setBounds(0, 0, 1130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente2, javax.swing.GroupLayout.PREFERRED_SIZE, 1179, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente2, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoThuonghieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoThuonghieu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoThuonghieu1ActionPerformed

    private void rdoChatlieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoChatlieu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoChatlieu1ActionPerformed

    private void rdoNSX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNSX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNSX1ActionPerformed

    private void rdoMausac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMausac1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMausac1ActionPerformed

    private void rdoSize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSize1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoSize1ActionPerformed

    private void rdodanhmuc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdodanhmuc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdodanhmuc1ActionPerformed

    private void btn_them1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_them1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_them1ActionPerformed

    private void btn_xoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xoa1ActionPerformed

    private void btn_LamMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LamMoi1ActionPerformed

    private void Btn_capNhat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_capNhat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_capNhat1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(them_Thuoc_Tinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(them_Thuoc_Tinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(them_Thuoc_Tinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(them_Thuoc_Tinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new them_Thuoc_Tinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.MyButton Btn_capNhat1;
    private swing.MyButton btn_LamMoi1;
    private swing.MyButton btn_them1;
    private swing.MyButton btn_xoa1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private swing.PanelBorder panelBorder10;
    private swing.PanelBorder panelBorder6;
    private swing.PanelBorder panelBorder7;
    private swing.PanelBorder panelBorder8;
    private swing.PanelBorder panelBorder9;
    private swing.PanelGradiente panelGradiente2;
    private javax.swing.JRadioButton rdoChatlieu1;
    private javax.swing.JRadioButton rdoMausac1;
    private javax.swing.JRadioButton rdoNSX1;
    private javax.swing.JRadioButton rdoSize1;
    private javax.swing.JRadioButton rdoThuonghieu1;
    private javax.swing.JRadioButton rdodanhmuc1;
    private swing.SearchText searchText2;
    // End of variables declaration//GEN-END:variables
}
